[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_twitter = "D4fyU4LYyMz5Ygvs3jyrdTHNMb2wxmV3Y2eyhpSENq4Z"

[programs.devnet]
solana_twitter = "D4fyU4LYyMz5Ygvs3jyrdTHNMb2wxmV3Y2eyhpSENq4Z"

[programs.mainnet]
solana_twitter = "D4fyU4LYyMz5Ygvs3jyrdTHNMb2wxmV3Y2eyhpSENq4Z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/amitpatel/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
